name: freelance_task
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  internet_connection_checker: ^3.0.1
  logger: ^2.5.0
  equatable: ^2.0.7
  go_router: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  analyzer: ^6.2.0  



flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
